name: Publish to AMO

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags and branches

      - name: Determine the current tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          jq --arg tag "${{ env.TAG }}" '.version = $tag' package.json > package.tmp.json
          mv package.tmp.json package.json
          jq --arg tag "${{ env.TAG }}" '.version = $tag' src/manifest.json > src/manifest.tmp.json
          mv src/manifest.tmp.json src/manifest.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch dependencies
        run: yarn install

      - name: Publish to AMO
        env:
          AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
          AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
        run: |
          npm run test
          npm run lint
          npx web-ext sign \
            --source-dir ./src \
            --api-key $AMO_API_KEY \
            --api-secret $AMO_API_SECRET \
            --channel listed \

      - name: Commit version update
        run: |
          git fetch origin main
          git checkout main
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add package.json src/manifest.json
          git commit -m "Update version to ${{ env.TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}